/*
 * Revenium Metering API
 * Revenium Metering API
 *
 * OpenAPI spec version: 1.16.0-SNAPSHOT
 * Contact: info@revenium.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.revenium.metering.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * RatingEventDTO
 */

@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-31T18:55:44.946581-04:00[America/New_York]")

public class RatingEventDTO {
  @SerializedName("sourceId")
  private String sourceId = null;

  @SerializedName("subscriptionId")
  private String subscriptionId = null;

  @SerializedName("payload")
  private Map<String, Object> payload = new HashMap<String, Object>();

  @SerializedName("sourceType")
  private String sourceType = null;

  public RatingEventDTO sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

   /**
   * the sourceId
   * @return sourceId
  **/
  @Schema(description = "the sourceId")
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }

  public RatingEventDTO subscriptionId(String subscriptionId) {
    this.subscriptionId = subscriptionId;
    return this;
  }

   /**
   * the subscriptionId
   * @return subscriptionId
  **/
  @Schema(description = "the subscriptionId")
  public String getSubscriptionId() {
    return subscriptionId;
  }

  public void setSubscriptionId(String subscriptionId) {
    this.subscriptionId = subscriptionId;
  }

  public RatingEventDTO payload(Map<String, Object> payload) {
    this.payload = payload;
    return this;
  }

  public RatingEventDTO putPayloadItem(String key, Object payloadItem) {
    this.payload.put(key, payloadItem);
    return this;
  }

   /**
   * The rating payload
   * @return payload
  **/
  @Schema(example = "{\"rating\":5}", required = true, description = "The rating payload")
  public Map<String, Object> getPayload() {
    return payload;
  }

  public void setPayload(Map<String, Object> payload) {
    this.payload = payload;
  }

  public RatingEventDTO sourceType(String sourceType) {
    this.sourceType = sourceType;
    return this;
  }

   /**
   * the source type
   * @return sourceType
  **/
  @Schema(description = "the source type")
  public String getSourceType() {
    return sourceType;
  }

  public void setSourceType(String sourceType) {
    this.sourceType = sourceType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatingEventDTO ratingEventDTO = (RatingEventDTO) o;
    return Objects.equals(this.sourceId, ratingEventDTO.sourceId) &&
        Objects.equals(this.subscriptionId, ratingEventDTO.subscriptionId) &&
        Objects.equals(this.payload, ratingEventDTO.payload) &&
        Objects.equals(this.sourceType, ratingEventDTO.sourceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceId, subscriptionId, payload, sourceType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatingEventDTO {\n");
    
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
