/*
 * Revenium Metering API
 * Revenium Metering API
 *
 * OpenAPI spec version: 1.16.0-SNAPSHOT
 * Contact: info@revenium.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.revenium.metering.api;

import io.revenium.metering.model.MeteringRequestDTO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for MeteringApi
 */
@Ignore
public class MeteringApiTest {

    private final MeteringApi api = new MeteringApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void ingestTest() throws Exception {
        String body = null;
        String xReveniumSubscriptionId = null;
        String xReveniumSourceId = null;
        String xReveniumSourceType = null;
        Object response = api.ingest(body, xReveniumSubscriptionId, xReveniumSourceId, xReveniumSourceType);

        // TODO: test validations
    }
    /**
     * Insert API metering data
     *
     * Insert API metering data
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void meterTest() throws Exception {
        MeteringRequestDTO body = null;
        Object response = api.meter(body);

        // TODO: test validations
    }
    /**
     * Determine if a ProductKey is valid or not
     *
     * Determine if a ProductKey is valid or not
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void validTest() throws Exception {
        String productKey = null;
        String application = null;
        Object response = api.valid(productKey, application);

        // TODO: test validations
    }
}
